# Generated by Django 6.0.3 on 2026-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationletter',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
