# Generated by Django 6.0.3 on 2026-05-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_add_ai_summary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationletter',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_letters', to='invoices.invoice'),
        ),
    ]
