# Generated by Django 6.0.3 on 2026-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_activitylog_delete_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
