# Generated by Django 6.0.3 on 2026-05-26 13:28

import django.db.models.deletion
import hw.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0003_cl_invoice_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hw.models._attachment_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hw.confirmationletter')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hw.invoice')),
            ],
        ),
    ]
