# Generated by Django 6.0.3 on 2026-05-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0007_hotel_model'),
        ('hw', '0007_userprofile'),
    ]

    operations = [
    ]
