# Generated by Django 6.0.3 on 2026-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0013_activitylog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
