# Generated by Django 6.0.3 on 2026-05-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0015_payment_cl_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationletter',
            name='confirmation_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='linked_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
