# Generated by Django 6.0.3 on 2026-06-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0018_rename_app_to_hw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], default='konoz', max_length=20)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='remittance/proof/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Remittance',
                'verbose_name_plural': 'Remittances',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='attachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='confirmationletter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hotel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reservation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serviceitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_number', models.CharField(max_length=100)),
                ('amount_sar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_lines', to='hw.invoice')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hw.remittance')),
            ],
            options={
                'verbose_name': 'Remittance Line',
                'verbose_name_plural': 'Remittance Lines',
            },
        ),
    ]
