# Generated by Django 6.0.3 on 2026-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0019_remittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='remittance_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
