# Generated by Django 6.0.3 on 2026-06-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0020_add_remittance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
