# Generated by Django 6.0.3 on 2026-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0021_add_receipt_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
