# Generated by Django 6.0.3 on 2026-06-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0022_add_remittance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationletter',
            name='check_in',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='confirmationletter',
            name='check_out',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='confirmationletter',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='confirmationletter',
            name='reservation_status',
            field=models.CharField(db_index=True, default='DEFINITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('visa', 'Visa/Services')], db_index=True, default='hotel', max_length=20),
        ),
        migrations.CreateModel(
            name='CancellationPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_number', models.CharField(max_length=50, unique=True)),
                ('cancellation_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('penalty_currency', models.CharField(default='SAR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_note', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='hw.confirmationletter')),
            ],
            options={
                'verbose_name': 'Cancellation Penalty',
                'verbose_name_plural': 'Cancellation Penalties',
                'ordering': ['-created_at'],
            },
        ),
    ]
