# Generated by Django 6.0.3 on 2026-06-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0023_alter_confirmationletter_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('PHONE', 'Nomor WA'), ('GROUP', 'Grup WA')], max_length=10)),
                ('target', models.CharField(max_length=100)),
                ('cl_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(choices=[('AUTO', 'Otomatis'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recap Log',
                'verbose_name_plural': 'Recap Logs',
            },
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='estimasi_tiba',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='pic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='pic_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('H1_GUEST', 'H-1 ke Tamu'), ('H0_GUEST', 'Hari H ke Tamu')], max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='hw.confirmationletter')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
            },
        ),
    ]
