# Generated by Django 6.0.3 on 2026-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0024_recaplog_confirmationletter_estimasi_tiba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WATarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100, unique=True)),
                ('target_type', models.CharField(choices=[('PHONE', 'Nomor WA'), ('GROUP', 'Grup WA')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WA Target',
                'verbose_name_plural': 'WA Targets',
                'ordering': ['label'],
            },
        ),
    ]
