# Generated by Django 6.0.3 on 2026-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0025_watarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('H1_GUEST', 'H-1 Sehari Sebelum'), ('H0_GUEST', 'H-0 Hari Check-in')], max_length=20, unique=True)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
            },
        ),
    ]
