# Generated by Django 6.0.3 on 2026-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0026_messagetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationletter',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ai_summary',
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='template_type',
            field=models.CharField(choices=[('H1_GUEST', 'H-1 Sehari Sebelum'), ('H0_GUEST', 'H-0 Hari Check-in'), ('RECAP_OPS', 'Rekap Harian')], max_length=20, unique=True),
        ),
    ]
