# Generated by Django 6.0.3 on 2026-07-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0027_remove_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationpenalty',
            name='penalty_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='remittanceline',
            name='amount_sar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='confirmationletter',
            constraint=models.UniqueConstraint(fields=('company', 'confirmation_number'), name='uniq_confirmation_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_type', 'invoice_number'), name='uniq_invoice_number_per_company_type'),
        ),
    ]
