# Generated by Django 6.0.3 on 2026-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0028_alter_cancellationpenalty_penalty_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='confirmationletter',
            index=models.Index(fields=['company', 'check_in'], name='hw_cl_company_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmationletter',
            index=models.Index(fields=['company', 'reservation_status'], name='hw_cl_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_type'], name='hw_invoice_company_type_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'due_date'], name='hw_invoice_company_due_idx'),
        ),
    ]
