# Generated by Django 6.0.3 on 2026-07-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0031_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reminder_target',
            field=models.CharField(choices=[('PIC', 'PIC'), ('GROUP', 'WhatsApp Group'), ('BOTH', 'PIC & Group')], default='GROUP', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='wa_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='WhatsApp Group'),
        ),
    ]
