# Generated by Django 6.0.3 on 2026-07-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0033_grouped_reminder_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_logs', to='hw.invoice')),
            ],
            options={
                'verbose_name': 'Billing Log',
                'verbose_name_plural': 'Billing Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
