# Generated by Django 6.0.3 on 2026-07-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0034_billinglog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
