# Generated by Django 6.0.3 on 2026-07-28 14:14

from django.db import migrations, models


def seed_roles(apps, schema_editor):
    """Give every existing account a profile and a role matching its old flags.

    Before RBAC the only distinctions were is_superuser and is_staff, so map
    them onto the closest new role: superuser -> admin, staff -> manager,
    everyone else -> staff. Nobody loses access they already had.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('hw', 'UserProfile')

    for user in User.objects.all().iterator():
        if user.is_superuser:
            role = 'admin'
        elif user.is_staff:
            role = 'manager'
        else:
            role = 'staff'
        profile, created = UserProfile.objects.get_or_create(
            user=user, defaults={'role': role, 'company_access': 'all'},
        )
        if not created:
            profile.role = role
            profile.company_access = 'all'
            profile.save(update_fields=['role', 'company_access'])


def unseed_roles(apps, schema_editor):
    """No-op: the columns themselves are dropped by the reverse AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0035_payment_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_access',
            field=models.CharField(choices=[('all', 'All companies'), ('konoz', 'Konoz United only'), ('ijabah', 'Ijabah only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=10),
        ),
        migrations.RunPython(seed_roles, unseed_roles),
    ]
