# Generated by Django 6.0.3 on 2026-08-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0038_userprofile_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('amount_sar', models.IntegerField()),
                ('reason', models.CharField(choices=[('initial', 'Initial'), ('revision', 'Revision'), ('transfer', 'Transfer'), ('cancellation', 'Cancellation'), ('correction', 'Correction')], max_length=20)),
                ('transfer_group', models.UUIDField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hw.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hw.invoice')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hw.cancellationpenalty')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hw.reservation')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hw.serviceitem')),
            ],
            options={
                'verbose_name': 'Allocation',
                'verbose_name_plural': 'Allocations',
                'ordering': ['date', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('amount_sar', models.IntegerField()),
                ('reason', models.CharField(choices=[('initial', 'Initial'), ('revision', 'Revision'), ('cancellation', 'Cancellation'), ('correction', 'Correction')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='hw.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='hw.invoice')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hw.cancellationpenalty')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hw.reservation')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hw.serviceitem')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['date', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('from_account', models.CharField(choices=[('client', 'Client'), ('sby', 'Surabaya'), ('pusat', 'Pusat'), ('fx', 'FX')], max_length=20)),
                ('to_account', models.CharField(choices=[('client', 'Client'), ('sby', 'Surabaya'), ('pusat', 'Pusat'), ('fx', 'FX')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='ledger/proof/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='hw.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='hw.remittance')),
                ('reservation_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.reservation')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='hw.cashmovement')),
            ],
            options={
                'verbose_name': 'Cash Movement',
                'verbose_name_plural': 'Cash Movements',
                'ordering': ['date', 'created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='ledger_cashmovement_from_ne_to')],
            },
        ),
    ]
