# Generated by Django 6.0.3 on 2026-08-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0039_allocation_charge_cashmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hw.client'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='hw.client'),
        ),
    ]
