# Generated by Django 6.0.3 on 2026-08-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0040_alter_allocation_client_alter_charge_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='service_item_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.serviceitem'),
        ),
    ]
