# Generated by Django 6.0.3 on 2026-08-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0041_cashmovement_service_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='hw.invoice'),
        ),
    ]
