# Generated by Django 6.0.3 on 2026-08-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0042_cashmovement_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='penalty_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.cancellationpenalty'),
        ),
    ]
