# Generated by Django 6.0.3 on 2026-08-07 10:23

import django.db.models.deletion
import hw.models.visit
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0043_cashmovement_penalty_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, default='konoz', max_length=20)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_lat', models.FloatField(blank=True, null=True)),
                ('checkin_lng', models.FloatField(blank=True, null=True)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='hw.client')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hw.models.visit._visit_photo_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hw.visit')),
            ],
            options={
                'verbose_name': 'Visit Photo',
                'verbose_name_plural': 'Visit Photos',
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['company', 'status'], name='hw_visit_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['company', 'scheduled_date'], name='hw_visit_company_date_idx'),
        ),
    ]
