# Generated by Django 6.0.3 on 2026-08-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0045_seed_visits_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='outcome',
            field=models.CharField(blank=True, choices=[('ORDER', 'Order received'), ('PROSPECT', 'Prospect / follow-up needed'), ('NO_INTEREST', 'No interest'), ('NOT_MET', 'Client not met')], default='', max_length=20),
        ),
    ]
