# Generated by Django 6.0.3 on 2026-08-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0046_visit_estimated_value_visit_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='pic_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='visit',
            name='pic_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
