# Generated by Django 6.0.3 on 2026-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0047_visit_pic_name_visit_pic_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
