# Generated by Django 6.0.3 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0048_visit_end_time_visit_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
