# Generated by Django 6.0.3 on 2026-08-11 07:55

import hw.models.landing
from django.db import migrations, models


NO_DELETE = ['create', 'edit', 'export', 'view']
EVERY     = ['create', 'delete', 'edit', 'export', 'view']
READ      = ['export', 'view']

GRANTS = {
    'manager': EVERY,
    'staff':   NO_DELETE,
    'viewer':  READ,
}


def grant_landing(apps, schema_editor):
    RoleDefinition = apps.get_model('hw', 'RoleDefinition')
    for slug, actions in GRANTS.items():
        row = RoleDefinition.objects.filter(slug=slug).first()
        if row is None or 'landing' in (row.permissions or {}):
            continue
        row.permissions = {**(row.permissions or {}), 'landing': list(actions)}
        row.save(update_fields=['permissions'])


def unseed_landing(apps, schema_editor):
    """No-op: reversing a module grant isn't meaningful once a business may
    have edited roles through /roles/ since."""


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0049_client_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], default='konoz', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=hw.models.landing._pricelist_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricelist',
                'verbose_name_plural': 'Pricelist',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], default='konoz', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('wa', models.CharField(blank=True, help_text='Nomor WhatsApp, mis. 6281234567890', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil di halaman publik')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anggota Tim',
                'verbose_name_plural': 'Anggota Tim',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(grant_landing, unseed_landing),
    ]
