# Generated by Django 6.0.3 on 2026-08-11 08:09

import hw.models.landing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0050_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to=hw.models.landing._team_photo_path),
        ),
    ]
