# Generated by Django 6.0.3 on 2026-08-13 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0051_teammember_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United'), ('ijabah', 'Ijabah')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('penalty__isnull', True), ('reservation__isnull', False), ('service_item__isnull', True)), models.Q(('penalty__isnull', True), ('reservation__isnull', True), ('service_item__isnull', False)), models.Q(('penalty__isnull', False), ('reservation__isnull', True), ('service_item__isnull', True)), _connector='OR'), name='ledger_allocation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('penalty__isnull', True), ('reservation__isnull', False), ('service_item__isnull', True)), models.Q(('penalty__isnull', True), ('reservation__isnull', True), ('service_item__isnull', False)), models.Q(('penalty__isnull', False), ('reservation__isnull', True), ('service_item__isnull', True)), _connector='OR'), name='ledger_charge_exactly_one_target'),
        ),
    ]
