# Generated by Django 6.0.3 on 2026-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0052_alter_client_company_alter_hotel_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='charge',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='confirmationletter',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_access',
            field=models.CharField(choices=[('all', 'All companies'), ('konoz', 'Konoz United only')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, default='konoz', max_length=20),
        ),
    ]
