# Generated by Django 6.0.3 on 2026-08-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0053_alter_allocation_company_alter_cashmovement_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
    ]
