# Generated by Django 5.2.8 on 2026-08-14 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0054_remove_invoice_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation_label__isnull', False), ('service_item_label__isnull', False)), models.Q(('penalty_label__isnull', False), ('reservation_label__isnull', False)), models.Q(('penalty_label__isnull', False), ('service_item_label__isnull', False)), _connector='OR', _negated=True), name='ledger_cashmovement_at_most_one_label'),
        ),
    ]
