# Generated by Django 6.0.3 on 2026-08-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0057_alter_invoice_add_client_status_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_sar',
        ),
    ]
