# Generated by Django 6.0.3 on 2026-08-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0058_remove_invoice_total_sar_stored_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_sar',
        ),
    ]
