# Generated by Django 6.0.3 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0059_remove_invoice_paid_sar_stored_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='received_in',
            field=models.CharField(choices=[('sby', 'Surabaya'), ('jkt', 'Jakarta'), ('pusat', 'Pusat (Direct)')], default='sby', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='from_account',
            field=models.CharField(choices=[('client', 'Client'), ('sby', 'Surabaya'), ('jkt', 'Jakarta'), ('pusat', 'Pusat'), ('fx', 'FX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='to_account',
            field=models.CharField(choices=[('client', 'Client'), ('sby', 'Surabaya'), ('jkt', 'Jakarta'), ('pusat', 'Pusat'), ('fx', 'FX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.CharField(choices=[('cash_sby', 'Kas Surabaya'), ('cash_jkt', 'Kas Jakarta'), ('cash_pusat', 'Kas Pusat (HQ)'), ('fx', 'Selisih Kurs'), ('receivable', 'Piutang Client'), ('income_hotel', 'Pendapatan Hotel'), ('income_service', 'Pendapatan Visa/Services'), ('income_penalty', 'Pendapatan Penalty'), ('expense_penalty', 'Beban Penalty'), ('equity', 'Modal')], max_length=50),
        ),
    ]
