# Generated by Django 5.2.8 on 2026-08-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0062_add_client_hotel_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationpenalty',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='hw.client'),
        ),
    ]
