# Generated by Django 5.2.8 on 2026-08-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0063_penalty_client_protect_to_setnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=12)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('is_postable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.CharField(blank=True, choices=[('konoz', 'Konoz United')], help_text='Kosong = berlaku untuk semua company', max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hw.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['asset', 'liability', 'income', 'expense', 'equity'])), name='ledgeraccount_type_valid'), models.CheckConstraint(condition=models.Q(('normal_balance__in', ['debit', 'credit'])), name='ledgeraccount_normal_balance_valid')],
            },
        ),
    ]
