# Generated by Django 5.2.8 on 2026-08-27 11:26

from django.db import migrations, models


PG_ADD_EXCLUSION = """
CREATE EXTENSION IF NOT EXISTS btree_gist;
ALTER TABLE hw_financialperiod
    ADD CONSTRAINT financialperiod_no_overlap_per_company
    EXCLUDE USING gist (
        company WITH =,
        daterange(date_from, date_to, '[]') WITH &&
    );
"""

PG_DROP_EXCLUSION = """
ALTER TABLE hw_financialperiod DROP CONSTRAINT IF EXISTS financialperiod_no_overlap_per_company;
"""


def add_pg_exclusion(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(PG_ADD_EXCLUSION)


def drop_pg_exclusion(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(PG_DROP_EXCLUSION)


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0064_ledgeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialperiod',
            name='company',
            field=models.CharField(choices=[('konoz', 'Konoz United')], db_index=True, default='konoz', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='date_to',
            field=models.DateField(),
        ),
        # Postgres-only defense in depth; SQLite dev relies on
        # FinancialPeriod.save() -> _assert_no_overlap().
        migrations.RunPython(add_pg_exclusion, drop_pg_exclusion),
    ]
