# Generated by Django 5.2.8 on 2026-08-27 13:20

import django.db.models.deletion
from django.db import migrations, models


def purge_v1_journal(apps, schema_editor):
    """v1 JournalEntry/JournalLine (signed amount_sar, string account) tidak
    punya data produksi — semua di branch finance-redesign, belum ke main.
    Buang baris dev lama supaya konversi ke skema v2 (FK account, debit/
    credit) bersih. Data historis dibangun ulang lewat migrate_to_journal
    (Fase 7)."""
    apps.get_model('hw', 'JournalLine').objects.all().delete()
    apps.get_model('hw', 'JournalEntry').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0066_seed_chart_of_accounts'),
    ]

    operations = [
        migrations.RunPython(purge_v1_journal, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='journalline',
            options={'ordering': ['journal_entry_id', 'line_no', 'id'], 'verbose_name': 'Journal Line', 'verbose_name_plural': 'Journal Lines'},
        ),
        migrations.RemoveConstraint(
            model_name='journalline',
            name='journal_line_amount_nonzero',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='amount_sar',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='seq',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='credit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalline',
            name='currency',
            field=models.CharField(default='SAR', max_length=3),
        ),
        migrations.AddField(
            model_name='journalline',
            name='debit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalline',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='line_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journalline',
            name='orig_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='orig_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='journalline',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.remittance'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals_of', to='hw.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hw.ledgeraccount'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hw.client'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hw.invoice'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='hw.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['reservation', 'account'], name='journal_res_acct_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='journal_line_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('debit', 0), ('credit__gt', 0)), _connector='OR'), name='journal_line_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('journal_entry', 'line_no'), name='journal_line_no_uniq'),
        ),
    ]
