# Generated by Django 5.2.8 on 2026-08-27 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0067_alter_journalline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('seq__isnull', False)), fields=('company', 'seq'), name='journal_entry_company_seq_uniq'),
        ),
    ]
