# Generated by Django 5.2.8 on 2026-08-28 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0069_journal_append_only_pg_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sar', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hw.paymentrecord')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.cancellationpenalty')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.reservation')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hw.serviceitem')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_sar__gt', 0)), name='paymentallocation_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('penalty__isnull', True), ('reservation__isnull', False), ('service_item__isnull', True)), models.Q(('penalty__isnull', True), ('reservation__isnull', True), ('service_item__isnull', False)), models.Q(('penalty__isnull', False), ('reservation__isnull', True), ('service_item__isnull', True)), _connector='OR'), name='paymentallocation_exactly_one_target')],
            },
        ),
    ]
