# Generated by Django 5.2.8 on 2026-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0070_paymentallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('allocate', 'Allocation'), ('transfer', 'Transfer'), ('refund', 'Refund'), ('penalty', 'Penalty'), ('remittance', 'Remittance'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
